apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  annotations:
    rt-quota: "1000"
    rt-period: "10000"
    task-1: "200,300,4000"
    task-2: "200,300,4000"

spec:
  schedulerName: rt-scheduler
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
